version: '2'
services:
    demo-postgresql:
        container_name: demo-postgresql
        image: postgres:9.5.4
        # volumes:
        #     - ~/volumes/jhipster/demo/postgresql/:/var/lib/postgresql/
        environment:
            - POSTGRES_USER=demo
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
