version: '2'
services:
    demo-terracotta-server:
        container_name: demo-terracotta-server
        image: anthonydahanne/terracotta-server-oss:5.0.0
        environment:
            - OFFHEAP_RESOURCE_SIZE=256
            - OFFHEAP_RESOURCE_UNIT=MB
            - OFFHEAP_RESOURCE_NAME=primary-server-resource
        ports:
            - 9510:9510
